baseurl = "http://www.smokeyfeet.dev"
languageCode = "en-us"
theme = "sf16"
title = "Smokey Feet 2016"

[params]
authorName = "Smokey Feet Crew"
description = "International Swing Dance Festival"
googleAnalytics = "xxx"
facebookUrl = "//facebook.com/Smokey-Feet-181498711899234"
#twitterUrl = "//twitter.com/smokeyfeet"
